### PR TITLE
`+` is reserved character

### PR DESCRIPTION
**Pull request by mcbuddha**
https://tools.ietf.org/html/rfc3986#section-2.2

### CODE REVIEW

**Comment by weavejester** [comment]
A reserved character doesn't mean we encode it. "/" is also a reserved character, but we obviously don't encode that.

**Comment by mcbuddha** [comment]
I guess clients could *not call* `url-encode` for the parts they don't want to encode (because they know that those are sub-delimiters). Without the PR it's pretty difficult to encode a `+` sign (if you know that it is not a sub-delimiter, but a query param or whatever else).

**Comment by weavejester** [comment]
If it's a query parameter, then `form-encode` should be used. Ring-Codec distinguishes between URL-encoding, and encoding data in the "x-www-form-urlencoded" format. Often the two formats are conflated, but they have different semantics.

**Comment by mcbuddha** [comment]
Got it! Thanks

**Comment by weavejester** [comment]
As an aside, the current functionality stems from a problem someone had with handling a URL like `http://example.com/tags/foo+bar`. When the last path segment was decoded with Java's URL decoder, it produced "foo bar". Correct if it was decoding a query string, but not necessarily for a path segment.

**Pull request closed without merging**
