### PR TITLE
Optimize percent-decode

### PR DESCRIPTION
**Pull request by nilern**
Stop re-parsing the percent-encoded chunk with `re-seq`. Also remove intermediate sequences.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR. Why did you inline `parse-bytes`? Why not put the loop in `parse-bytes`? Do you have benchmarks for performance before and after?

**Comment by nilern** [comment]
I thought it better to inline a function with such an awkward precondition ("must match this regex..."). Although I suppose it already had that precondition, so it was a bit orthogonal to the optimization. In any case, I should have mentioned this.

A quick bench based on some test example was about 50% faster. Basically I just checked that it was actually faster, I could benchmark more if you want.

**Comment by weavejester** [comment]
Rather than inlining `parse-bytes`, can you instead put the new code in that function instead? Could you also make the internal variables (like `ci` and `bi`) a little more descriptive?

If you test the before and after function with Criterium, can you also add the output of that to this PR as a comment so we have a reference that people can refer back to in future?

**Comment by nilern** [comment]
Of course.

**Comment by nilern** [comment]
The results from my sanity benchmark:

# Before

```clojure
user=> (crit/bench (codec/percent-decode "foo%FE%FF%00%2Fbar" "UTF-16"))
Evaluation count : 618960 in 60 samples of 10316 calls.
             Execution time mean : 97,466064 µs
    Execution time std-deviation : 1,427946 µs
   Execution time lower quantile : 96,070529 µs ( 2,5%)
   Execution time upper quantile : 99,159458 µs (97,5%)
                   Overhead used : 13,943488 ns

Found 1 outliers in 60 samples (1,6667 %)
	low-severe	 1 (1,6667 %)
 Variance from outliers : 1,6389 % Variance is slightly inflated by outliers
```
# After

```clojure
user=> (crit/bench (codec/percent-decode "foo%FE%FF%00%2Fbar" "UTF-16"))
Evaluation count : 1216500 in 60 samples of 20275 calls.
             Execution time mean : 49,266600 µs
    Execution time std-deviation : 2,942700 µs
   Execution time lower quantile : 47,739405 µs ( 2,5%)
   Execution time upper quantile : 58,222833 µs (97,5%)
                   Overhead used : 13,601526 ns

Found 8 outliers in 60 samples (13,3333 %)
	low-severe	 2 (3,3333 %)
	low-mild	 6 (10,0000 %)
 Variance from outliers : 45,0770 % Variance is moderately inflated by outliers
```

**Comment by weavejester** [comment]
Thanks! Could you squash your two commits down? Then I'll merge it in and cut a release.

**Pull request merged**
